### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by michael-duke** [spydaspider/AwesomeBookProject#3]
## Awesome Books ES6 Project
Good work implemting the required taks for this project 😄 

- Code is well split among the modules.
- UI is nice and user-friendly, also nice touch on the notification.
- Kindly make the date human readable, you can do that by using Luxon's DateTime class and formatted, use the docs.
- Optional change:
  - If you could make some methods non-static that would be better so when creating a Book instance you can create multiple book collections who each have an add and remove book for their respective instance.

**Comment by spydaspider** [comment]
Thanks
